# Generated by Django 3.2.11 on 2022-01-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('nombreAutor', models.CharField(max_length=255)),
                ('apellidoAutor', models.CharField(max_length=255)),
                ('apellidoAutor2', models.CharField(max_length=255)),
                ('editorial', models.CharField(max_length=255)),
                ('generos', models.CharField(max_length=255)),
            ],
        ),
    ]
