# Generated by Django 3.2.11 on 2022-01-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('segundoApellido', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Género',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='apellidoAutor',
            new_name='autor',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='apellidoAutor2',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='nombreAutor',
        ),
    ]
