# Generated by Django 3.2.11 on 2022-01-13 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros_api', '0002_auto_20220113_0135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Género',
            new_name='Genero',
        ),
    ]
