# Generated by Django 3.2.11 on 2022-01-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros_api', '0004_auto_20220113_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fechaPublicacion',
            field=models.DateField(),
        ),
    ]
