# Generated by Django 3.2.11 on 2022-01-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros_api', '0005_alter_libro_fechapublicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='fechaNacimiento',
            field=models.DateField(auto_now=True),
        ),
    ]
