# Generated by Django 3.2.11 on 2022-01-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros_api', '0006_autor_fechanacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fechaPublicacion',
            field=models.DateField(auto_now=True),
        ),
    ]
