# Generated by Django 3.2.11 on 2022-01-13 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros_api', '0007_alter_libro_fechapublicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='numeroPaginas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros_api.autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros_api.editorial'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='generos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros_api.genero'),
        ),
    ]
