# Generated by Django 3.2.11 on 2022-01-13 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros_api', '0008_auto_20220113_0551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autore'},
        ),
        migrations.AlterModelOptions(
            name='editorial',
            options={'verbose_name': 'Editoriale'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'Género'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'Libro'},
        ),
        migrations.AlterField(
            model_name='autor',
            name='apellido',
            field=models.CharField(max_length=255, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='fechaNacimiento',
            field=models.DateField(blank=True, verbose_name='Fecha nacimiento'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='segundoApellido',
            field=models.CharField(blank=True, max_length=255, verbose_name='Segundo apellido'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros_api.autor', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros_api.editorial', verbose_name='Editorial'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fechaPublicacion',
            field=models.DateField(verbose_name='Fecha publicación'),
        ),
        migrations.RemoveField(
            model_name='libro',
            name='generos',
        ),
        migrations.AddField(
            model_name='libro',
            name='generos',
            field=models.ManyToManyField(to='libros_api.Genero'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='numeroPaginas',
            field=models.IntegerField(default=0, verbose_name='Número de páginas'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
