# Generated by Django 3.2.11 on 2022-01-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros_api', '0010_auto_20220113_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha nacimiento'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fechaPublicacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha publicación'),
        ),
    ]
