# Generated by Django 3.2.11 on 2022-01-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros_api', '0011_auto_20220113_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='generos',
            field=models.ManyToManyField(blank=True, null=True, to='libros_api.Genero', verbose_name='Géneros'),
        ),
    ]
