# Generated by Django 3.2.11 on 2022-01-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros_api', '0012_alter_libro_generos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autor',
        ),
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.ManyToManyField(blank=True, to='libros_api.Autor', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='generos',
            field=models.ManyToManyField(blank=True, to='libros_api.Genero', verbose_name='Géneros'),
        ),
    ]
