# Generated by Django 3.2.11 on 2022-01-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros_api', '0013_auto_20220113_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='autor',
            new_name='autores',
        ),
    ]
